/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/// <reference types="vite/client" />
interface ImportMetaEnv {
  readonly VITE_API_URL: string
  readonly VITE_AUTH_URL: string
  readonly VITE_BUCKET_URL: string
  readonly VITE_STRIPE_SECRET_KEY: string
  readonly VITE_STRIPE_PUBLISHABLE_KEY: string
  readonly VITE_STRIPE_ACCOUNT_ID: string
  readonly VITE_GOOGLE_MAPS_API_KEY: string
}
interface ImportMeta {
  readonly env: ImportMetaEnv
}